name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/nextjs-blog-app:latest --push .

      - name: Start SSH Agent and Add Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VPS_GG_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.VPS_SERVER_IP }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa
          ssh-add -l

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no godhanigopal@${{ secrets.VPS_SERVER_IP }} << 'EOF'
            docker pull ${{ secrets.DOCKER_USERNAME }}/nextjs-blog-app:latest
            docker stop nextjs-blog-app || true
            docker rm nextjs-blog-app || true
            docker run -d --name nextjs-blog-app --network live -p :3000 ${{ secrets.DOCKER_USERNAME }}/nextjs-blog-app:latest
          EOF
